#!/bin/bash

if git rev-list HEAD -n1 --pretty=oneline | grep "^WIP \[UNSTAGED\]$" > /dev/null
  then
    git reset HEAD^ > /dev/null
fi
if git rev-list HEAD -n1 --pretty=oneline | grep "^WIP \[STAGED\]$" > /dev/null
  then
    git reset --soft HEAD^ > /dev/null
fi
git status --short
